### ISSUE TITLE
Renamer

### ISSUE THREAD

**Issue by wookie104** [christophedc0/Dump#1]
I am using docker on unraid and I am not sure if it is an issue or lack of understanding on my part. I got every other part of the config working (using test locations to fox borders) but when I try renamer I always get 

12:17 AM INFO: Finished sync_gdrive
12:17 AM ERROR: Path not found: /data/placeholder

but my config shows: (I commented it out for now so it runs)
#renamer:
#  run: false
#  dry_run: true
#  asset_folders: true
#  action_type: copy
#  print_only_renames: false
#  library_names:
#    - Xmas
#  source_dir: /data
#  source_overrides:
#    - /data/chrisdc
#    - /data/Drazz
#    - /data/solen
#    - /data/dsaq
#    - /data/bz
#    - /data/stupifierr
#  destination_dir: /destination
#  collection_threshold: 99
#  radarr:
#    - name: radarr
#  sonarr:
#    - name: sonarr

fix_border:
  run: true
  input_folder: /data (eventually replace with /destination)
  output_folder: /data/source (eventually replace with /destination)
  border_color: none
  overwrite_existing: true
  resize: false
  bottom_only: false

When I created the docker I used these as the mount points:

    -v /mnt/user/appdata/Plex-Meta-Manager/spp/config:/config \
    -v /mnt/user/appdata/Plex-Meta-Manager/config/assets:/destination \
    -v /mnt/user/appdata/plex-metadata/posters:/data \
    -v /mnt/user/data/media/movies/:/data/media/movies \

**Comment by christophedc0** [comment]
This is actually meant to be a jumpstart for configuring these things and not serve as a 1-on-1 guide, but.. when you look at the SPP github and follow the link to Drazz’s github, you’ll stumble across this:
```# Where your ingest movies folder is (THe source and destination should not be the same directory)
  source_dir: /path/to/posters/ <--- Lowest priority
  # What posters you'd like to override the souce dir with. This dir will take priority for assets over source_dir
  # To not use any override, simply leave it blank or remove it from the config
  # Can be a single dir or a list of dirs
  source_overrides: 
    - /path/to/posters/override/ <--- Middle priority
    - /path/to/posters/override2/ <--- Highest priority ```

So basically the reason you got that error, is probably because you don’t have `/data/placeholder` in the container.
