### ISSUE TITLE
Two gdrive syncs writing to same directory

### ISSUE THREAD

**Issue by jwoodhouse** [christophedc0/Dump#28]
https://github.com/christophedc0/Dump/blob/2c053c9591bfb59d23293dea2db27a7b35f00203/DAPS/config.yml#L137-L140

Hey, just a heads up that theres 2 gdrive IDs writing to the /data/majorgiant folder in your config.

This seems to cause some overwrites and re-syncs on every run. I fixed it on my end by updating the second entry to write to /data/majorgiant-collection

Thanks for the configs btw!

**Comment by christophedc0** [comment]
Adapted typo, please be aware that there are more drives being added in the nfo file.
The config will not be updated, since it will serve as an example.

Thanks for letting me know this issue !
